services:
  temporal: # Temporal dev server
    container_name: temporal
    build:
      context: .
      dockerfile: temporal_cli.Dockerfile
    command: ["server", "start-dev", "--ip", "0.0.0.0"]
    ports:
      - "7233:7233"   # gRPC endpoint
      - "7234:7234"   # HTTP endpoint for health checks
      - "8233:8233"   # HTTP endpoint for UI
      - "60743:60743"   # HTTP endpoint for metrics
    networks:
      - temporal-network

  worker: # Temporal worker
    container_name: temporal-worker
    build:
      context: .
      dockerfile: temporal_worker.Dockerfile
    depends_on:
      - temporal
    networks:
      - temporal-network
    restart: unless-stopped
    environment:
      - TEMPORAL_HOST=temporal:7233

  # Reference: https://www.jaegertracing.io/docs/2.8/getting-started/
  jaeger:
    container_name: jaeger
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"   # accept OTLP over gRPC
      - "4318:4318"   # accept OTLP over HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - temporal-network
    restart: unless-stopped

networks:
  temporal-network:
    driver: bridge