services:
  temporal: # Temporal dev server
    container_name: temporal
    build:
      context: .
      dockerfile: temporal_cli.Dockerfile
    command: ["server", "start-dev", "--ip", "0.0.0.0"]
    ports:
      - "7233:7233"   # gRPC endpoint
      - "7234:7234"   # HTTP endpoint for health checks
      - "8233:8233"   # HTTP endpoint for UI
      - "60743:60743"   # HTTP endpoint for metrics
    networks:
      - temporal-network

  worker: # Temporal worker
    container_name: temporal-worker
    build:
      context: .
      dockerfile: temporal_worker.Dockerfile
    depends_on:
      - temporal
      - otel-collector
    networks:
      - temporal-network
    restart: unless-stopped
    environment:
      - TEMPORAL_HOST=temporal:7233
      - OTLP_TRACE_ENDPOINT=http://otel-collector:4317

  # Reference: https://opentelemetry.io/docs/collector/
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger
    networks:
      - temporal-network
    restart: unless-stopped

  # Reference: https://www.jaegertracing.io/docs/2.8/getting-started/
  jaeger:
    container_name: jaeger
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"   # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - temporal-network
    restart: unless-stopped

networks:
  temporal-network:
    driver: bridge