receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  cumulativetodelta: # required for Dynatrace
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlphttp/dynatrace:
    endpoint: "https://${DYNATRACE_TENANT}.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DYNATRACE_API_TOKEN}"
  prometheus: # exposes a Prometheus endpoint
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "otel-collector"
  debug:
    verbosity: detailed

service:
  pipelines:
    traces/jaeger:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
      # exporters: [otlp/jaeger, otlphttp/dynatrace]

    metrics/prometheus:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    # metrics/dynatrace:
    #   receivers: [otlp]
    #   processors: [cumulativetodelta, batch]
    #   exporters: [otlphttp/dynatrace]