global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself for self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape metrics from OpenTelemetry Collector's Prometheus exporter
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s

  # Scrape OpenTelemetry Collector's own metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s