receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus: # exposes a Prometheus endpoint
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "otel-collector"
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "temporal-logs"
    mapping:
      mode: "raw"
    retry:
      enabled: true
      max_requests: 5
      initial_interval: 100ms
      max_interval: 1s
  debug:
    verbosity: detailed

service:
  pipelines:
    # Open source observability platform
    traces/jaeger:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics/prometheus:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs/elasticsearch:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
